name: Run Agent on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run prediction sample
        run: |
          python - <<'PY'
          import requests
          print('Demo: Would call /predict on deployed orchestrator in prod')
          PY
